### ISSUE TITLE
javascript error / no sound

### ISSUE THREAD

**Issue by dandante** [Bubobubobubobubo/Topos#4]
Hello,

This looks really cool. I can't get it to produce any sound. I hit control-G and then pasted in some code:

```
mod(24) && euclid($('a'), 5, 8) && d({s:'bd'});
mod(24) && euclid($('b'), 2, 8) && d({s:'cp'});
mod(24) && euclid($('c'), 7, 8) && d({s:'hh'});
```

I put my cursor on the first line and hit control-enter. Maybe the screen flashes a bit, it's hard to say, but I don't hear any sound. 

I do see errors in the javascript console happening quite frequently, in multiple browsers:

```
VM63252:7 ReferenceError: d is not defined
    at UserAPI.eval (eval at <anonymous> (index-28a25d7a.js:56:6820), <anonymous>:3:43)
    at index-28a25d7a.js:56:6883
    at new Promise (<anonymous>)
    at tryCatchWrapper (index-28a25d7a.js:56:6796)
    at tryEvaluate (index-28a25d7a.js:56:7005)
    at index-28a25d7a.js:56:7849
```

Thanks

**Comment by Bubobubobubobubo** [comment]
Hello!

Yes, I already changed the API since that post I made! You can play sounds using a different (and more human friendly) syntax now. Try `sound('bd').out()`.

You can add qualifiers to your sound like `sound('bd').speed(2).out()`. There is no documentation available for the moment but you can find all the qualifiers in the file `src/Sound.ts`.

**Comment by Bubobubobubobubo** [comment]
Solved with integrated documentation
